<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-DeliveryTrackingSystem-e4c87a70-30dd-46e6-a0b0-c0e2089fd8b8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Identity\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cargobell.Data\Cargobell.Data.csproj" />
    <ProjectReference Include="..\Cargobell.Services\Cargobell.Services.csproj" />
    <ProjectReference Include="..\Cargobell.Shared\Cargobell.Shared.csproj" />
  </ItemGroup>

</Project>
